#!/bin/bash
# Copyright (C) 2020 Lumina Networks, Inc. All Rights Reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this distribution,
# and is available at http://www.eclipse.org/legal/epl-v10.html
#
cfgfile=$(mktemp XXX.yaml)
echo "steps:" >> $cfgfile
IFS=, read -ra services <<< "$1"
for service in ${services[@]}; 
do
    echo "  - k8s_wait_pod:" >> $cfgfile
    echo "      field_selector: status.phase=Running" >> $cfgfile
    echo "      label_selector: app=$service" >> $cfgfile
done


$(dirname $0)/saf-setup --config $cfgfile